# @author Alejandro Galue <agalue@opennms.org>

---
apiVersion: v1
kind: Service
metadata:
  name: cassandra
  namespace: opennms
spec:

---
apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: cassandra
  namespace: opennms
spec:
  replicas: 0