# @author Alejandro Galue <agalue@opennms.org>

---
apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: kafka
  namespace: opennms
spec:
  template:
    spec:
      containers:
      - name: kafka
        env:
        - name: HOSTNAME_COMMAND
          value: "echo 'docker.for.mac.localhost'"


