# @author Alejandro Galue <agalue@opennms.org>

---
apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: kafka
spec:
  template:
    spec:
      containers:
      - name: kafka
        env:
        - name: HOSTNAME_COMMAND
          value: curl -H Metadata:true "http://169.254.169.254/metadata/instance/network/interface/0/ipv4/ipAddress/0/publicIpAddress?api-version=2017-08-01&format=text"
        resources:
          limits:
            memory: 1Gi
          requests:
            memory: 512Mi
          $patch: replace


