apiVersion: v1
kind: Pod
metadata:
  name: debug
  namespace: opennms
  labels:
    app: debug
spec:
  dnsPolicy: None
  dnsConfig:
    nameservers:
      -  10.0.96.190
    searches:
      - opennms.svc.cluster.local
      - svc.cluster.local
      - cluster.local
  containers:
  - name: debug
    image: ubuntu:eoan
    imagePullPolicy: IfNotPresent
    command: ["/bin/bash", "-ec", "while :; do date; sleep 3600; done"]
