apiVersion: apps/v1
kind: Deployment
metadata:
  name: dnscache
  namespace: opennms
  labels:
    app: dnscache
spec:
  replicas: 2
  selector:
    matchLabels:
      app: dnscache
  template:
    metadata:
      labels:
        app: dnscache
    spec:
      terminationGracePeriodSeconds: 300
      securityContext:
        runAsUser: 0
        fsGroup: 1000
      containers:
      - name: dnscache
        image: deployable/unbound:latest
        imagePullPolicy: IfNotPresent
        command: ["/usr/sbin/unbound", "-c", "/data/unbound.conf"]
        volumeMounts:
          - name: config
            mountPath: /data
        resources:
          limits:
            memory: 512Mi
            cpu: 1
          requests:
            memory: 256Mi
            cpu: 200m
      volumes:
      - name: config
        configMap:
          name: dnscache-conf
---
apiVersion: v1
kind: Service
metadata:
  name: dnscache
  namespace: opennms
  labels:
    app: dnscache
spec:
  ports:
  - port: 53
    protocol: UDP
    name: dnsudp
  - port: 53
    protocol: TCP
    name: dnstcp
  selector:
    app: dnscache
