# @author Alejandro Galue <agalue@opennms.org>

---
apiVersion: v1
kind: Service
metadata:
  name: ext-kafka-manager
  labels:
    app: kafka-manager
    deployment: drift
  annotations:
    dns.alpha.kubernetes.io/external: kafka-manager.k8s.opennms.org.
spec:
  type: LoadBalancer
  ports:
  - port: 80
    targetPort: 9000
  selector:
    app: kafka-manager

---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: kafka-manager
  labels:
    app: kafka-manager
    deployment: drift
spec:
  replicas: 1
  selector:
    matchLabels:
      app: kafka-manager
  template:
    metadata:
      labels:
        app: kafka-manager
        deployment: drift
    spec:
      containers:
      - name: kafka-manager
        image: sheepkiller/kafka-manager:stable
        imagePullPolicy: IfNotPresent
        env:
        - name: ZK_HOSTS
          value: zookeeper.default.svc.cluster.local:2181/kafka
        - name: APPLICATION_SECRET
          value: opennms
        ports:
        - containerPort: 9000
          name: http
        readinessProbe:
          httpGet:
            path: /
            port: http
          initialDelaySeconds: 10
          timeoutSeconds: 5
        livenessProbe:
          httpGet:
            path: /
            port: http
          initialDelaySeconds: 30
          periodSeconds: 60