# @author Alejandro Galue <agalue@opennms.org>
#
# Warning: this excludes Cassandra to reduce the overhead on Minikube

---
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: opennms

commonLabels:
  environment: minikube

commonAnnotations:
  owner: agalue@opennms.org

resources:
- namespace/opennms.yaml
- manifests/postgresql.yaml
- manifests/zookeeper.yaml
- manifests/kafka.yaml
- manifests/elasticsearch.data.yaml
- manifests/opennms.core.yaml
- manifests/opennms.minion.yaml
- manifests/opennms.sentinel.yaml

configMapGenerator:
- name: opennms-config
  files:
  - config/onms-core-init.sh
  - config/onms-minion-init.sh
  - config/onms-sentinel-features.xml
  - config/onms-sentinel-init.sh
  - config/onms-ui-init.sh
- name: common-settings
  literals:
  - TIMEZONE=America/New_York
  - OPENNMS_INSTANCE_ID=OpenNMS
  - CASSANDRA_CLUSTER_NAME=OpenNMS
  - CASSANDRA_REPLICATION_FACTOR="1"

generatorOptions:
  disableNameSuffixHash: true

secretGenerator:
- name: onms-passwords
  env: minikube/passwords.env
  type: Opaque

patchesJson6902:
- path: minikube/patches/postgres.yaml 
  target:
    group: apps
    version: v1
    kind: StatefulSet
    name: postgres
- path: minikube/patches/zookeeper.yaml
  target:
    group: apps
    version: v1
    kind: StatefulSet
    name: zk
- path: minikube/patches/kafka.yaml
  target:
    group: apps
    version: v1
    kind: StatefulSet
    name: kafka
- path: minikube/patches/elasticsearch.yaml
  target:
    group: apps
    version: v1
    kind: StatefulSet
    name: esdata
- path: minikube/patches/opennms.core.yaml
  target:
    group: apps
    version: v1
    kind: StatefulSet
    name: onms
- path: minikube/patches/opennms.minion.yaml
  target:
    group: apps
    version: v1
    kind: StatefulSet
    name: minion
- path: minikube/patches/opennms.sentinel.yaml
  target:
    group: apps
    version: v1
    kind: Deployment
    name: sentinel
