apiVersion: v1
kind: Pod
metadata:
  name: udpgen-m0
  namespace: opennms
  labels:
    app: udpgen
spec:
  securityContext:
    runAsUser: 1000
    fsGroup: 1000
  containers:
  - name: udpgen
    image: agalue/udpgen:latest
    args: [ "/usr/local/bin/udpgen", "-i", "-x", "netflow5", "-r", "3", "-h", "minion-0.minion.opennms.svc.cluster.local", "-p", "8877" ]
    imagePullPolicy: IfNotPresent
    resources:
      limits:
        memory: 512Mi
        cpu: 200m
      requests:
        memory: 256Mi
        cpu: 100m
---
apiVersion: v1
kind: Pod
metadata:
  name: udpgen-m1
  namespace: opennms
  labels:
    app: udpgen
spec:
  securityContext:
    runAsUser: 1000
    fsGroup: 1000
  containers:
  - name: udpgen
    image: agalue/udpgen:latest
    args: [ "/usr/local/bin/udpgen", "-i", "-x", "netflow5", "-r", "3", "-h", "minion-1.minion.opennms.svc.cluster.local", "-p", "8877" ]
    imagePullPolicy: IfNotPresent
    resources:
      limits:
        memory: 512Mi
        cpu: 200m
      requests:
        memory: 256Mi
        cpu: 100m

# minion Netflow-9-Listener port 4729/udp
# minion Netflow-5-Listener port 8877/udp
