# @author Alejandro Galue <agalue@opennms.org>

---
apiVersion: v1
kind: Service
metadata:
  name: cassandra-reaper
spec:

---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: cassandra-reaper
spec:
  replicas: 0