# @author Alejandro Galue <agalue@opennms.org>

---
apiVersion: v1
kind: Service
metadata:
  name: kibana
  namespace: opennms
spec:

---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: kibana
  namespace: opennms
spec:
  replicas: 0