# @author Alejandro Galue <agalue@opennms.org>
#
# http://cassandra-reaper.io/docs/configuration/docker_vars/

---
apiVersion: v1
kind: Service
metadata:
  name: cassandra-reaper
  namespace: opennms
  labels:
    app: cassandra-reaper
    deployment: drift
spec:
  clusterIP: None
  ports:
  - port: 8080
    name: http
  selector:
    app: cassandra-reaper

---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: cassandra-reaper
  namespace: opennms
  labels:
    app: cassandra-reaper
    deployment: drift
spec:
  replicas: 1
  selector:
    matchLabels:
      app: cassandra-reaper
  template:
    metadata:
      labels:
        app: cassandra-reaper
        deployment: drift
    spec:
      initContainers:
      - name: dependencies
        image: waisbrot/wait
        imagePullPolicy: IfNotPresent
        env:
        - name: TARGETS
          value: cassandra.opennms.svc.cluster.local:9042
        - name: TIMEOUT
          value: '600'
      - name: init-database
        image: cassandra:3.11.4
        imagePullPolicy: IfNotPresent
        command: [ sh, -c, 'cqlsh -e $CQL $CASSANDRA_HOST' ]
        env:
        - name: CASSANDRA_HOST
          value: cassandra.opennms.svc.cluster.local
        - name: REPFACTOR # Must match CASSANDRA_REPFACTOR from opennms.core.yaml
          value: '2'
        - name: CQL
          value: "CREATE KEYSPACE IF NOT EXISTS reaper_db WITH replication = {'class' : 'NetworkTopologyStrategy', 'Main' : $(REPFACTOR) };"
      containers:
      - name: cassandra-reaper
        image: thelastpickle/cassandra-reaper:1.4.0
        imagePullPolicy: IfNotPresent
        env:
        - name: REAPER_JMX_AUTH_USERNAME # See config-map cassandra-config
          value: cassandra
        - name: REAPER_JMX_AUTH_PASSWORD # See config-map cassandra-config
          value: cassandra
        - name: REAPER_STORAGE_TYPE
          value: cassandra
        - name: REAPER_CASS_CONTACT_POINTS
          value: "[ cassandra.opennms.svc.cluster.local ]"
        - name: REAPER_CASS_CLUSTER_NAME # See CASSANDRA_CLUSTER_NAME from cassandra.yaml
          value: OpenNMS
        ports:
        - containerPort: 8080
          name: http
        - containerPort: 8081
          name: http-admin
        resources:
          limits:
            cpu: 200m
            memory: 512Mi
          requests:
            cpu: 50m
            memory: 128Mi
        readinessProbe:
          tcpSocket:
            port: http
          initialDelaySeconds: 30
          periodSeconds: 15
        livenessProbe:
          tcpSocket:
            port: http
          initialDelaySeconds: 60
          periodSeconds: 60
