# @author Alejandro Galue <agalue@opennms.org>
#
# WARNING:
# - MAX_HEAP_SIZE should be consistent with resources.requests.memory
# - CASSANDRA_DC should match config/opennms-core/newts.cql
# - The cassandra user (uid: 999, gid: 999) cannot be used in OpenShift by default.
#
# TODO:
# - Improve a PreStop lifecycle hook to perform a decomission when scaling down the cluster.
#   A script that looks for a specific file (copied through kubectl) can help to decide which kind of task to execute.
#   In theory, persistent volumes should also be deleted as well.
# - Take a look at https://github.com/instaclustr/cassandra-operator
# - Take a look at https://github.com/scylladb/scylla-code-samples/tree/master/kubernetes-scylla

---
apiVersion: v1
kind: Service
metadata:
  name: cassandra
  namespace: opennms
  labels:
    app: cassandra
    deployment: drift
spec:
  clusterIP: None
  ports:
  - port: 7000
    name: intra-node
  - port: 7001
    name: tls-intra-node
  - port: 7199
    name: jmx
  - port: 9042
    name: cql
  selector:
    app: cassandra

---
apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: cassandra
  namespace: opennms
  labels:
    app: cassandra
    deployment: drift
spec:
  serviceName: cassandra
  replicas: 3
  selector:
    matchLabels:
      app: cassandra
  template:
    metadata:
      labels:
        app: cassandra
        deployment: drift
    spec:
      terminationGracePeriodSeconds: 600
      containers:
      - name: cassandra
        image: cassandra:3.11.3
        imagePullPolicy: IfNotPresent
        env:
        - name: MAX_HEAP_SIZE
          value: 2G
        - name: HEAP_NEWSIZE
          value: 2G
        - name: CASSANDRA_SEEDS
          value: cassandra-0.cassandra.opennms.svc.cluster.local
        - name: CASSANDRA_CLUSTER_NAME
          value: OpenNMS
        - name: CASSANDRA_ENDPOINT_SNITCH
          value: GossipingPropertyFileSnitch
        - name: CASSANDRA_DC
          value: Main
        - name: CASSANDRA_RACK
          valueFrom:
            fieldRef:
              fieldPath: metadata.name # TODO spec.nodeName should be more correct, or create a policy to avoid having 2 instances on the same machine
        ports:
        - containerPort: 7000
          name: intra-node
        - containerPort: 7001
          name: tls-intra-node
        - containerPort: 7199
          name: jmx
        - containerPort: 9042
          name: cql
        volumeMounts:
        - name: cassandra-data
          mountPath: /cassandra_data
        resources:
          limits:
            cpu: 4
            memory: 4Gi
          requests:
            cpu: 2
            memory: 2Gi
        securityContext:
          capabilities:
            add:
            - IPC_LOCK
        lifecycle:
          preStop:
            exec:
              command: # TODO What about decommissioning ?
              - bash
              - -c
              - nodetool drain
        readinessProbe:
          exec:
            command:
            - bash
            - -c
            - 'if [[ $(nodetool status -r | grep $HOSTNAME) == *"UN"* ]]; then exit 0; else exit 1; fi'
          initialDelaySeconds: 30
          periodSeconds: 10
        livenessProbe:
          tcpSocket:
            port: cql
          initialDelaySeconds: 120
          periodSeconds: 60
  volumeClaimTemplates:
  - metadata:
      name: cassandra-data
    spec:
      accessModes:
      - ReadWriteOnce
      storageClassName: ssd
      resources:
        requests:
          storage: 20Gi
