# @author Alejandro Galue <agalue@opennms.org>

---
apiVersion: certmanager.k8s.io/v1alpha1
kind: ClusterIssuer
metadata:
  name: letsencrypt-prod
  namespace: opennms
  labels:
    deployment: drift
spec:
  acme:
    server: https://acme-v02.api.letsencrypt.org/directory
    email: agalue@opennms.org
    privateKeySecretRef:
      name: letsencrypt-prod
    http01: {}

---
apiVersion: certmanager.k8s.io/v1alpha1
kind: Certificate
metadata:
  name: k8s-opennms-org-tls
  namespace: opennms
  labels:
    deployment: drift
spec:
  secretName: k8s-opennms-org
  issuerRef:
    name: letsencrypt-prod
    kind: ClusterIssuer
  commonName: k8s.opennms.org
  dnsNames:
    - grafana.k8s.opennms.org
    - kafka-manager.k8s.opennms.org
    - kibana.k8s.opennms.org
    - onms.k8s.opennms.org
    - onmsui.k8s.opennms.org
    - kafka.k8s.opennms.org
  acme:
    config:
      - http01:
          ingressClass: nginx
        domains:
          - grafana.k8s.opennms.org
          - kafka-manager.k8s.opennms.org
          - kibana.k8s.opennms.org
          - onms.k8s.opennms.org
          - onmsui.k8s.opennms.org

