# @author Alejandro Galue <agalue@opennms.org>
#
# WARNING:
# - The elasticsearch user (uid: 1000, gid: 1000) cannot be used in OpenShift by default.
#
# TODO:
# - Install the OpenNMS Elasticsearch Plugin required for the Flows Deep Dive Tool
#   Plugin Version 1.0.0 requires ES 6.2.4, Version 1.1.0 requires ES 6.5.4

---
apiVersion: v1
kind: Service
metadata:
  name: esdata
  namespace: opennms
  labels:
    app: elasticsearch
    deployment: drift
    role: esdata
spec:
  clusterIP: None
  ports:
  - port: 9200
    name: http
  - port: 9300
    name: transport
  selector:
    role: esdata

---
apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: esdata
  namespace: opennms
  labels:
    app: elasticsearch
    deployment: drift
    role: esdata
spec:
  serviceName: esdata
  replicas: 3
  selector:
    matchLabels:
      role: esdata
  template:
    metadata:
      labels:
        app: elasticsearch
        deployment: drift
        role: esdata
    spec:
      terminationGracePeriodSeconds: 300
      securityContext:
        fsGroup: 1000
      initContainers:
      - name: init-sysctl
        image: busybox
        command:
        - sysctl
        - -w
        - vm.max_map_count=262144
        securityContext:
          privileged: true
      - name: dependencies
        image: waisbrot/wait
        imagePullPolicy: IfNotPresent
        env:
        - name: TARGETS
          value: esmaster.opennms.svc.cluster.local:9200
        - name: TIMEOUT
          value: '600'
      containers:
      - name: esdata
        image: docker.elastic.co/elasticsearch/elasticsearch:6.5.4
        imagePullPolicy: IfNotPresent
        securityContext:
          runAsUser: 1000
          capabilities:
            add:
            - IPC_LOCK
            - SYS_RESOURCE
        ports:
        - containerPort: 9200
          name: http
        - containerPort: 9300
          name: transport
        env:
        - name: cluster.name
          value: OpenNMS
        - name: node.name
          valueFrom:
            fieldRef:
              fieldPath: metadata.name
        - name: xpack.security.enabled
          value: 'false'
        - name: discovery.zen.ping.unicast.hosts
          value: esmaster.opennms.svc.cluster.local
        - name: discovery.zen.minimum_master_nodes
          value: '2' # Requires a minimum of 3 replicas
        - name: node.master
          value: 'false'
        - name: node.data
          value: 'true'
        - name: node.ingest
          value: 'true'
        - name: http.cors.enabled
          value: 'true'
        - name: http.cors.allow-origin
          value: '*'
        - name: MEM_TOTAL_MB
          valueFrom:
            resourceFieldRef:
              resource: requests.memory
              divisor: 1Mi
        - name: ES_JAVA_OPTS # TODO jvm.options default will be used if Xms/Xmx are not passed
          value: -Xms$(MEM_TOTAL_MB)m -Xmx$(MEM_TOTAL_MB)m
        - name: ELASTIC_PASSWORD
          valueFrom:
            secretKeyRef:
              key: ELASTICSEARCH
              name: onms-passwords
        volumeMounts:
        - name: es-data
          mountPath: /usr/share/elasticsearch/data
        resources:
          limits:
            cpu: 4
            memory: 4Gi
          requests:
            cpu: 2
            memory: 2Gi
        readinessProbe:
          tcpSocket:
            port: http
          initialDelaySeconds: 30
          periodSeconds: 15
        livenessProbe:
          tcpSocket:
            port: http
          initialDelaySeconds: 60
          periodSeconds: 60
  volumeClaimTemplates:
  - metadata:
      name: es-data
    spec:
      accessModes:
      - ReadWriteOnce
      storageClassName: ssd
      resources:
        requests:
          storage: 20Gi
