# @author Alejandro Galue <agalue@opennms.org>
#
# ES_JAVA_OPTS should be consistent with resources.requests.memory
#
# TODO
# - minimum_master_nodes should be 2, but that enters in conflict with the dns-controller and the readinessProbe.
#   That's because the FQDN are not reach until the readinessProbe says so, and ES won't start until the master are initialized.

---
apiVersion: v1
kind: Service
metadata:
  name: esdata
  labels:
    app: elasticsearch
    deployment: drift
    role: esdata
spec:
  clusterIP: None
  ports:
  - port: 9200
  selector:
    role: esdata

---
apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: esdata
  labels:
    app: elasticsearch
    deployment: drift
    role: esdata
spec:
  serviceName: esdata
  replicas: 3
  selector:
    matchLabels:
      role: esdata
  template:
    metadata:
      labels:
        app: elasticsearch
        deployment: drift
        role: esdata
    spec:
      initContainers:
      - name: init-sysctl
        image: busybox
        command:
        - sysctl
        - -w
        - vm.max_map_count=262144
        securityContext:
          privileged: true
      - name: wait-for-dependencies
        image: waisbrot/wait
        imagePullPolicy: IfNotPresent
        env:
        - name: TARGETS
          value: esmaster.default.svc.cluster.local:9200
        - name: TIMEOUT
          value: '600'
      containers:
      - name: esdata
        image: docker.elastic.co/elasticsearch/elasticsearch:6.2.4
        imagePullPolicy: IfNotPresent
        ports:
        - containerPort: 9200
          name: http
        - containerPort: 9300
          name: transport
        env:
        - name: cluster.name
          value: OpenNMS
        - name: node.name
          valueFrom:
            fieldRef:
              fieldPath: metadata.name
        - name: xpack.license.self_generated.type
          value: basic # Use 'trial', to enable authentication
        - name: xpack.security.enabled
          value: 'true'
        - name: discovery.zen.ping.unicast.hosts
          value: esmaster.default.svc.cluster.local
        - name: discovery.zen.minimum_master_nodes
          value: '1'
        - name: node.master
          value: 'false'
        - name: node.data
          value: 'true'
        - name: node.ingest
          value: 'true'
        - name: http.cors.enabled
          value: 'true'
        - name: http.cors.allow-origin
          value: '*'
        - name: ES_JAVA_OPTS
          value: -Xms2g -Xmx2g
        - name: ELASTIC_PASSWORD
          value: elastic
        volumeMounts:
        - name: es-data
          mountPath: /usr/share/elasticsearch/data
        resources:
          limits:
            cpu: 4
            memory: 4Gi
          requests:
            cpu: 2
            memory: 2Gi
        readinessProbe:
          httpGet:
            path: /
            port: http
          initialDelaySeconds: 15
        livenessProbe:
          httpGet:
            path: /
            port: http
          initialDelaySeconds: 60
          periodSeconds: 60
  volumeClaimTemplates:
  - metadata:
      name: es-data
    spec:
      accessModes:
      - ReadWriteOnce
      storageClassName: aws-ebs
      resources:
        requests:
          storage: 20Gi