# @author Alejandro Galue <agalue@opennms.org>
#
# The dns-controller will automatically create a CNAME for each host pointing to the Ingress ELB when --watch-ingress=true is applied.
#
# TODO What about this ? helm install stable/nginx-ingress
# TODO For certificates with Let's Encrypt, consider kube-lego (installed via helm).
---
apiVersion: extensions/v1beta1
kind: Ingress
metadata:
  name: ingress-rules
  namespace: opennms
  labels:
    deployment: drift
  annotations:
    kubernetes.io/ingress.class: nginx
    ingress.kubernetes.io/affinity: cookie
    ingress.kubernetes.io/session-cookie-name: route
    ingress.kubernetes.io/session-cookie-hash: sha1
    dns.alpha.kubernetes.io/external: ingress.k8s.opennms.org.
spec:
  rules:
    - host: grafana.k8s.opennms.org
      http:
        paths:
          - path: /
            backend:
              serviceName: grafana
              servicePort: 3000
    - host: kafka-manager.k8s.opennms.org
      http:
        paths:
          - path: /
            backend:
              serviceName: kafka-manager
              servicePort: 9000
    - host: kibana.k8s.opennms.org
      http:
        paths:
          - path: /
            backend:
              serviceName: kibana
              servicePort: 5601
    - host: onms.k8s.opennms.org
      http:
        paths:
          - path: /
            backend:
              serviceName: opennms-core
              servicePort: 8980
    - host: onmsui.k8s.opennms.org
      http:
        paths:
          - path: /
            backend:
              serviceName: opennms-ui
              servicePort: 8980

# An alternative to the following is creating Route53 entries through Terraform to avoid having an ELB as an entry point for Minions.
# The Route53 entries should point to all the hosts.
# Another alternative is use the K8S Hostname on the advertised listener, and then use that on Minions.
---
apiVersion: v1
kind: Service
metadata:
  name: ext-kafka
  namespace: opennms
  labels:
    app: kafka
    deployment: drift
  annotations:
    dns.alpha.kubernetes.io/external: kafka.k8s.opennms.org.
spec:
  type: LoadBalancer
  ports:
  - port: 9094
    targetPort: 9094
  selector:
    app: kafka