# @author Alejandro Galue <agalue@opennms.org>

---
apiVersion: v1
kind: Service
metadata:
  name: grafana
  labels:
    app: grafana
    deployment: drift
spec:
  clusterIP: None
  ports:
  - port: 3000
  selector:
    app: grafana

---
apiVersion: v1
kind: Service
metadata:
  name: ext-grafana
  labels:
    app: grafana
    deployment: drift
  annotations:
    dns.alpha.kubernetes.io/external: grafana.k8s.opennms.org.
spec:
  type: LoadBalancer
  ports:
  - port: 80
    targetPort: 3000
  selector:
    app: grafana

---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: grafana
  labels:
    app: grafana
    deployment: drift
spec:
  replicas: 2
  selector:
    matchLabels:
      app: grafana
  template:
    metadata:
      labels:
        app: grafana
        deployment: drift
    spec:
      initContainers:
        - name: initialize-database
          image: postgres:10.4
          imagePullPolicy: IfNotPresent
          command:
          - sh
          - /bin/grafana-init.sh
          env:
            - name: PGHOST
              value: postgresql.default.svc.cluster.local
            - name: PGPORT
              value: '5432'
            - name: PGUSER
              value: postgres
            - name: PGPASSWORD
              value: postgres
            - name: DATABASE_NAME
              value: grafana
            - name: DATABASE_USER
              value: grafana
            - name: DATABASE_PASSWORD
              value: grafana
          volumeMounts:
          - name: grafana
            mountPath: /bin/grafana-init.sh
            subPath: grafana-init.sh
      containers:
      - name: grafana
        image: grafana/grafana:5.2.2
        imagePullPolicy: IfNotPresent
        ports:
        - containerPort: 3000
          name: http
        env:
          - name: GF_SECURITY_ADMIN_PASSWORD
            value: opennms
          - name: GF_INSTALL_PLUGINS
            value: opennms-helm-app
          - name: GF_DATABASE_TYPE
            value: postgres
          - name: GF_DATABASE_HOST
            value: postgresql.default.svc.cluster.local:5432
          - name: GF_DATABASE_NAME
            value: grafana
          - name: GF_DATABASE_USER
            value: grafana
          - name: GF_DATABASE_PASSWORD
            value: grafana
          - name: GF_SESSION_PROVIDER
            value: postgres
          - name: GF_SESSION_PROVIDER_CONFIG
            value: user=grafana password=grafana host=postgresql.default.svc.cluster.local port=5432 dbname=grafana sslmode=disable
        readinessProbe:
          httpGet:
            path: /
            port: http
          initialDelaySeconds: 10
          timeoutSeconds: 5
        livenessProbe:
          httpGet:
            path: /
            port: http
          initialDelaySeconds: 30
          periodSeconds: 60
      volumes:
      - name: grafana
        configMap:
          name: grafana
