# @author Alejandro Galue <agalue@opennms.org>
#
# The password for the grafana user in PostgreSQL is plain text here due to GF_SESSION_PROVIDER_CONFIG

---
apiVersion: v1
kind: Service
metadata:
  name: grafana
  namespace: opennms
  labels:
    app: grafana
    deployment: drift
spec:
  clusterIP: None
  ports:
  - port: 3000
  selector:
    app: grafana

---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: grafana
  namespace: opennms
  labels:
    app: grafana
    deployment: drift
spec:
  replicas: 2
  selector:
    matchLabels:
      app: grafana
  template:
    metadata:
      labels:
        app: grafana
        deployment: drift
    spec:
      initContainers:
      - name: initialize-database
        image: postgres:10.4
        imagePullPolicy: IfNotPresent
        command:
        - sh
        - /bin/grafana-init.sh
        env:
          - name: PGHOST
            value: postgresql.opennms.svc.cluster.local
          - name: PGPORT
            value: '5432'
          - name: PGUSER
            value: postgres
          - name: PGPASSWORD
            valueFrom:
              secretKeyRef:
                key: POSTGRES
                name: onms-passwords
          - name: GF_DATABASE_NAME
            value: grafana
          - name: GF_DATABASE_USER
            value: grafana
          - name: GF_DATABASE_PASSWORD
            value: grafana
        volumeMounts:
        - name: opennms-config
          mountPath: /bin/grafana-init.sh
          subPath: grafana-init.sh
      containers:
      - name: grafana
        image: grafana/grafana:5.2.4
        imagePullPolicy: IfNotPresent
        ports:
        - containerPort: 3000
          name: http
        env:
          - name: GF_SECURITY_ADMIN_PASSWORD
            valueFrom:
              secretKeyRef:
                key: GRAFANA_UI_ADMIN
                name: onms-passwords
          - name: GF_INSTALL_PLUGINS
            value: opennms-helm-app
          - name: GF_DATABASE_TYPE
            value: postgres
          - name: GF_DATABASE_HOST
            value: postgresql.opennms.svc.cluster.local:5432
          - name: GF_DATABASE_NAME
            value: grafana
          - name: GF_DATABASE_USER
            value: grafana
          - name: GF_DATABASE_PASSWORD
            value: grafana
          - name: GF_SESSION_PROVIDER
            value: postgres
          - name: GF_SESSION_PROVIDER_CONFIG # The password field should match GF_DATABASE_PASSWORD
            value: user=grafana password=grafana host=postgresql.opennms.svc.cluster.local port=5432 dbname=grafana sslmode=disable
        readinessProbe:
          httpGet:
            path: /
            port: http
          initialDelaySeconds: 10
          periodSeconds: 10
        livenessProbe:
          httpGet:
            path: /
            port: http
          initialDelaySeconds: 30
          periodSeconds: 60
      volumes:
      - name: opennms-config
        configMap:
          name: opennms-config
