# @author Alejandro Galue <agalue@opennms.org>
#
# WARNING:
# - The password for the grafana user in PostgreSQL is plain text here due to GF_SESSION_PROVIDER_CONFIG

---
apiVersion: v1
kind: Service
metadata:
  name: grafana
  namespace: opennms
  labels:
    app: grafana
    deployment: drift
spec:
  ports:
  - port: 3000
  selector:
    app: grafana

---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: grafana
  namespace: opennms
  labels:
    app: grafana
    deployment: drift
spec:
  replicas: 2
  selector:
    matchLabels:
      app: grafana
  template:
    metadata:
      labels:
        app: grafana
        deployment: drift
    spec:
      initContainers:
      - name: dependencies
        image: waisbrot/wait
        imagePullPolicy: IfNotPresent
        env:
        - name: TARGETS
          value: postgresql.opennms.svc.cluster.local:5432
        - name: TIMEOUT
          value: '600'
      - name: init-database
        image: postgres:10.7-alpine
        imagePullPolicy: IfNotPresent
        command:
        - sh
        - /bin/grafana-init.sh
        env:
        - name: PGHOST
          value: postgresql.opennms.svc.cluster.local
        - name: PGPORT
          value: '5432'
        - name: PGUSER
          value: postgres
        - name: PGPASSWORD
          valueFrom:
            secretKeyRef:
              key: POSTGRES
              name: onms-passwords
        - name: GF_DATABASE_NAME
          value: grafana
        - name: GF_DATABASE_USER
          value: grafana
        - name: GF_DATABASE_PASSWORD
          value: grafana
        volumeMounts:
        - name: opennms-config
          mountPath: /bin/grafana-init.sh
          subPath: grafana-init.sh
      containers:
      - name: grafana-helm
        #image: opennms/helm:3.0.0
        image: opennms/helm:bleeding # Not good for production
        imagePullPolicy: IfNotPresent
        ports:
        - containerPort: 3000
          name: http
        env:
        - name: TZ
          value: America/New_York
        - name: GF_SECURITY_ADMIN_PASSWORD
          valueFrom:
            secretKeyRef:
              key: GRAFANA_UI_ADMIN
              name: onms-passwords
        - name: GF_DATABASE_TYPE
          value: postgres
        - name: GF_DATABASE_HOST
          value: postgresql.opennms.svc.cluster.local:5432
        - name: GF_DATABASE_NAME
          value: grafana
        - name: GF_DATABASE_USER
          value: grafana
        - name: GF_DATABASE_PASSWORD
          value: grafana
        - name: GF_SESSION_PROVIDER
          value: postgres
        - name: GF_SESSION_PROVIDER_CONFIG # dbname, user and password fields should match GF_DATABASE_* environment variables
          value: dbname=grafana user=grafana password=grafana host=postgresql.opennms.svc.cluster.local port=5432 sslmode=disable
        readinessProbe:
          httpGet:
            path: /
            port: http
          initialDelaySeconds: 10
          periodSeconds: 10
        livenessProbe:
          httpGet:
            path: /
            port: http
          initialDelaySeconds: 30
          periodSeconds: 60
      volumes:
      - name: opennms-config
        configMap:
          name: opennms-config
