# @author Alejandro Galue <agalue@opennms.org>
#
# A one time Job to enable OpenNMS Helm and creating the data sources on Grafana

---
apiVersion: batch/v1
kind: Job
metadata:
  name: helm-init
  namespace: opennms
  labels:
    app: grafana
    deployment: drift
spec:
  template:
    spec:
      containers:
      - name: grafana
        image: grafana/grafana:5.2.4
        imagePullPolicy: IfNotPresent
        command:
          - sh
          - /bin/helm-init.sh
        env:
          - name: GF_SECURITY_ADMIN_PASSWORD
            value: opennms
          - name: GRAFANA_URL
            value: http://grafana.opennms.svc.cluster.local:3000
          - name: ONMS_URL
            value: http://onmsui.k8s.opennms.org/opennms
          - name: ONMS_USER
            value: admin
          - name: ONMS_PASSWD
            value: admin
        volumeMounts:
        - name: grafana
          mountPath: /bin/helm-init.sh
          subPath: helm-init.sh
      restartPolicy: Never
      volumes:
      - name: grafana
        configMap:
          name: grafana
