# @author Alejandro Galue <agalue@opennms.org>
#
# A one time Job to configure SASL SCRAM Accounts

---
apiVersion: batch/v1
kind: Job
metadata:
  name: kafka-users
  namespace: opennms
  labels:
    app: kafka
spec:
  ttlSecondsAfterFinished: 120
  template:
    spec:
      restartPolicy: Never
      initContainers:
      - name: dependencies
        image: waisbrot/wait
        imagePullPolicy: IfNotPresent
        env:
        - name: TARGETS
          value: kafka.opennms.svc.cluster.local:9092
        - name: TIMEOUT
          value: '600'
      containers:
      - name: init-users
        image: wurstmeister/kafka:2.12-2.4.0
        imagePullPolicy: IfNotPresent
        command:
        - bash
        - /bin/kafka-init.sh
        env:
        - name: TZ
          valueFrom:
            configMapKeyRef:
              key: TIMEZONE
              name: common-settings
        - name: ZOOKEEPER
          value: zookeeper.opennms.svc.cluster.local:2181/kafka
        - name: KAFKA_ADMIN_USER
          valueFrom:
            secretKeyRef:
              key: KAFKA_ADMIN_USER
              name: kafka-jaas
        - name: KAFKA_ADMIN_PASSWORD
          valueFrom:
            secretKeyRef:
              key: KAFKA_ADMIN_PASSWORD
              name: kafka-jaas
        - name: KAFKA_CLIENT_USER
          valueFrom:
            secretKeyRef:
              key: KAFKA_CLIENT_USER
              name: kafka-jaas
        - name: KAFKA_CLIENT_PASSWORD
          valueFrom:
            secretKeyRef:
              key: KAFKA_CLIENT_PASSWORD
              name: kafka-jaas
        volumeMounts:
        - name: init-scripts
          mountPath: /bin/kafka-init.sh
          subPath: kafka-init.sh
      volumes:
      - name: init-scripts
        configMap:
          name: init-scripts
