# @author Alejandro Galue <agalue@opennms.org>
#
# Kafka Converter Tool implemented in Go.
# This takes a given GPB payload from a topic and puts its JSON representation into another topic

---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: kafka-converter
  namespace: opennms
  labels:
    app: kafka-converter
    deployment: drift
spec:
  replicas: 1
  selector:
    matchLabels:
      app: kafka-converter
  template:
    metadata:
      labels:
        app: kafka-converter
        deployment: drift
    spec:
      initContainers:
      - name: dependencies
        image: waisbrot/wait
        imagePullPolicy: IfNotPresent
        env:
        - name: TARGETS
          value: kafka.opennms.svc.cluster.local:9092
        - name: TIMEOUT
          value: '600'
      containers:
      - name: kafka-converter
        image: agalue/kafka-converter-go:latest
        imagePullPolicy: Always
        env:
        - name: BOOTSTRAP_SERVERS
          value: kafka.opennms.svc.cluster.local:9092
        - name: APP_ID
          value: Converter
        - name: SOURCE_KIND
          value: alarms
        - name: INSTANCE_ID
          valueFrom:
            configMapKeyRef:
              key: OPENNMS_INSTANCE_ID
              name: common-settings
        - name: SOURCE_TOPIC # Check org.opennms.features.kafka.producer.cfg at the OpenNMS server
          value: $(INSTANCE_ID)-alarms
        - name: DEST_TOPIC
          value: $(INSTANCE_ID)-alarms-json
        - name: CONSUMER_AUTO_OFFSET_RESET
          value: latest
        - name: CONSUMER_MAX_PARTITION_FETCH_BYTES
          value: '5000000'
        - name: PROCUCER_MAX_REQUEST_SIZE
          value: '5000000'
        resources:
          limits:
            memory: 128Mi
            cpu: 100m
