# @author Alejandro Galue <agalue@opennms.org>
#
# WARNING: The kibana user (uid: 1000, gid: 1000) cannot be used in OpenShift by default.

---
apiVersion: v1
kind: Service
metadata:
  name: kibana
  namespace: opennms
  labels:
    app: kibana
    deployment: drift
spec:
  clusterIP: None
  ports:
  - port: 5601
  selector:
    app: kibana

---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: kibana
  namespace: opennms
  labels:
    app: kibana
    deployment: drift
spec:
  replicas: 1
  selector:
    matchLabels:
      app: kibana
  template:
    metadata:
      labels:
        app: kibana
        deployment: drift
    spec:
      initContainers:
      - name: check-elasticsearch-ready
        image: busybox
        imagePullPolicy: IfNotPresent
        command:
        - sh
        - -c
        - 'until wget -q $ELASTICSEARCH_URL >/dev/null; do echo "$(date) - Waiting for $ELASTICSEARCH_URL..."; sleep 5; done'
        env:
        - name: ELASTICSEARCH_URL
          value: http://esdata.opennms.svc.cluster.local:9200
      containers:
      - name: kibana
        image: docker.elastic.co/kibana/kibana:6.2.4
        imagePullPolicy: IfNotPresent
        env:
        - name: SERVER_NAME
          valueFrom:
            fieldRef:
              fieldPath: metadata.name
        - name: ELASTICSEARCH_URL
          value: http://esdata.opennms.svc.cluster.local:9200
        - name: ELASTICSEARCH_USERNAME
          value: elastic
        - name: ELASTICSEARCH_PASSWORD
          value: elastic
        ports:
        - containerPort: 5601
          name: http
        readinessProbe:
          httpGet:
            path: /
            port: http
          initialDelaySeconds: 10
          periodSeconds: 10
        livenessProbe:
          httpGet:
            path: /
            port: http
          initialDelaySeconds: 60
          periodSeconds: 60
