# @author Alejandro Galue <agalue@opennms.org>

---
namespace: opennms

resources:
- namespace.yaml
- postgresql.yaml
- zookeeper.yaml
- kafka.yaml
- kafka.converter.yaml
- kafka.manager.yaml
- cassandra.yaml
- cassandra.reaper.yaml
- elasticsearch.master.yaml
- elasticsearch.data.yaml
- elastic-hq.yaml
- kibana.yaml
- opennms.core.yaml
- opennms.minion.yaml
- opennms.sentinel.yaml
- opennms.alec.yaml
- opennms.ui.yaml
- grafana.yaml
- grafana.helm.yaml
- hasura.yaml
- jaeger.yaml
- external-access.yaml
- event-watcher.yaml

configMapGenerator:
- name: opennms-config
  files:
  - config/grafana-init.sh
  - config/helm-init.sh
  - config/onms-alec-init.sh
  - config/onms-core-init.sh
  - config/onms-minion-init.sh
  - config/onms-sentinel-init.sh
  - config/onms-ui-init.sh
  - config/onms-ui-nfs.sh
- name: common-settings
  literals:
  - DOMAIN=aws.agalue.net
  - TIMEZONE=America/New_York
  - OPENNMS_INSTANCE_ID=OpenNMS
  - CASSANDRA_CLUSTER_NAME=OpenNMS
  - CASSANDRA_DC=Main
  - CASSANDRA_REPLICATION_FACTOR=2
  - ELASTIC_REPLICATION_FACTOR=2
  - ELASTIC_INDEX_STRATEGY_FLOWS=daily
  - KAFKA_NUM_PARTITIONS=6
  - MINION_LOCATION=Kubernetes

secretGenerator:
- name: onms-passwords
  type: Opaque
  literals:
  - POSTGRES_PASSWORD=postgres
  - OPENNMS_DB_PASSWORD=opennms
  - OPENNMS_UI_ADMIN_PASSWORD=admin
  - GRAFANA_UI_ADMIN_PASSWORD=opennms
  - GRAFANA_DB_USERNAME=grafana
  - GRAFANA_DB_PASSWORD=grafana
  - ELASTICSEARCH_PASSWORD=elastic
  - KAFKA_MANAGER_APPLICATION_SECRET=0p3nNMS
  - KAFKA_MANAGER_USERNAME=opennms
  - KAFKA_MANAGER_PASSWORD=0p3nNMS
  - HASURA_GRAPHQL_ACCESS_KEY=0p3nNMS

generatorOptions:
  disableNameSuffixHash: true
  annotations:
    owner: agalue@opennms.org
