# @author Alejandro Galue <agalue@opennms.org>
#
# Sentinel is required only for Processing Flows and Telemetry Data.
#
# NOTES:
# - It is perfectly valid to have all the required configuration files on a config-map,
#   and then mount those files to the overlay directory, instead of using an initContainer.
#
# WARNING:
# - The sentinel user (uid: 999, gid: 997) cannot be used in OpenShift by default.
# - The default images are based on OpenJDK, but Oracle JDK is recommended for production.
# - The image tag bleeding refers to the upcoming version of OpenNMS (unstable)
#
# Java 8 Issues:
# - -XX:+UnlockExperimentalVMOptions and -XX:+UseCGroupMemoryLimitForHeap won't work
# - -XX:ParallelGCThreads and -XX:ConcGCThreads might require to be updated.
#    Although, Runtime.getRuntime().availableProcessors() seems to respect the CPU limitations.

---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: sentinel
  namespace: opennms
  labels:
    app: sentinel
    deployment: drift
spec:
  replicas: 2
  selector:
    matchLabels:
      app: sentinel
  template:
    metadata:
      labels:
        app: sentinel
        deployment: drift
    spec:
      terminationGracePeriodSeconds: 60
      affinity:
        podAntiAffinity:
          preferredDuringSchedulingIgnoredDuringExecution:
          - weight: 100
            podAffinityTerm:
              topologyKey: kubernetes.io/hostname
              labelSelector:
                matchExpressions:
                - key: app
                  operator: In
                  values:
                  - onms
      initContainers:
      # Requires the same image/version used at runtime: sentinel
      - name: init-config
        image: agalue/sentinel:23.0.2-oracle-jdk8u201
        #image: opennms/sentinel:bleeding # Not good for production
        imagePullPolicy: IfNotPresent
        command: [ bash, /init.sh ]
        env:
        - name: INSTANCE_ID # Must be the same on all OpenNMS, Sentinels and Minions
          value: OpenNMS
        - name: KAFKA_SERVER
          value: kafka.opennms.svc.cluster.local
        - name: KAFKA_GROUP_ID
          value: Sentinel
        - name: CASSANDRA_SERVER
          value: cassandra.opennms.svc.cluster.local
        - name: ELASTIC_SERVER
          value: esdata.opennms.svc.cluster.local
        - name: ELASTIC_PASSWORD
          valueFrom:
            secretKeyRef:
              key: ELASTICSEARCH
              name: onms-passwords
        volumeMounts:
        - name: etc-overlay
          mountPath: /etc-overlay
        - name: opennms-config
          mountPath: /init.sh
          subPath: onms-sentinel-init.sh
      - name: dependencies
        image: waisbrot/wait
        imagePullPolicy: IfNotPresent
        env:
        - name: TARGETS
          value: opennms-core.opennms.svc.cluster.local:8980
        - name: TIMEOUT
          value: '600'
      containers:
      - name: sentinel
        image: agalue/sentinel:23.0.2-oracle-jdk8u201
        #image: opennms/sentinel:bleeding # Not good for production
        imagePullPolicy: IfNotPresent
        args:
          - -d
        ports:
        - containerPort: 8301
          name: karaf
        env:
        - name: MEM_TOTAL_MB
          valueFrom:
            resourceFieldRef:
              resource: requests.memory
              divisor: 1Mi
        - name: JAVA_OPTS
          value: -XX:+UseG1GC -Xms$(MEM_TOTAL_MB)m -Xmx$(MEM_TOTAL_MB)m -XX:+PrintFlagsFinal
        - name: POSTGRES_HOST
          value: postgresql.opennms.svc.cluster.local
        - name: POSTGRES_PORT
          value: '5432'
        - name: POSTGRES_USER
          value: postgres
        - name: POSTGRES_PASSWORD
          valueFrom:
            secretKeyRef:
              key: POSTGRES
              name: onms-passwords
        - name: POSTGRES_DB
          value: opennms
        - name: OPENNMS_HTTP_URL
          value: http://opennms-core.opennms.svc.cluster.local:8980/opennms
        - name: SENTINEL_LOCATION
          value: Sentinel
        - name: OPENNMS_HTTP_USER
          value: admin
        - name: OPENNMS_HTTP_PASS
          valueFrom:
            secretKeyRef:
              key: OPENNMS_UI_ADMIN
              name: onms-passwords
        volumeMounts:
        - name: etc-overlay
          mountPath: /opt/sentinel-etc-overlay
        - name: opennms-config # WARNING: This is for H23 only. Do not use it with H24+
          mountPath: /opt/sentinel/deploy/features.xml
          subPath: onms-sentinel-features.xml
        resources:
          limits:
            cpu: 1
            memory: 2Gi
          requests:
            cpu: 500m
            memory: 1Gi
        readinessProbe:
          tcpSocket:
            port: karaf
          initialDelaySeconds: 15
          periodSeconds: 10
        livenessProbe:
          exec:
            command:
            - bash
            - -c
            - 'if /opt/sentinel/bin/client health:check | grep --quiet "Everything is awesome"; then exit 0; else exit 1; fi'
          initialDelaySeconds: 60
          periodSeconds: 60
      volumes:
      - name: etc-overlay
        emptyDir: {}
      - name: opennms-config
        configMap:
          name: opennms-config
