# @author Alejandro Galue <agalue@opennms.org>
#
# NOTES:
# - It is perfectly valid to have all the required configuration files on a config-map,
#   and then mount those files to the overlay directory, instead of using an initContainer.
#   That said, without the intelligence to guard against upgrades through the initContainer
#   script, if you opt for using config-maps, you have to prepare the config giles on the PV
#   prior upgrading the version of OpenNMS on the chosen image.
#
# WARNING:
# - This deployment will have a persistent volume for /opt/opennms/etc to track the configuration changes.
# - The opennms process runs as root, which is not allowed on OpenShift
# - The default images are based on OpenJDK, but Oracle JDK is recommended for production.
# - The image tag bleeding refers to the upcoming version of OpenNMS (unstable)
#
# Java 8 Issues:
# - -XX:+UnlockExperimentalVMOptions and -XX:+UseCGroupMemoryLimitForHeap won't work
# - -XX:ParallelGCThreads and -XX:ConcGCThreads might require to be updated.
#    Although, Runtime.getRuntime().availableProcessors() seems to respect the CPU limitations.
#
# TODO:
# - Potential tools for managing /opt/opennms/etc:
#   https://vapor-ware.github.io/ksync/
#   https://github.com//kubernetes/git-sync
#   https://gitkube.sh
# - Add a lifecycle.preStart to execute a "git commit" of the current state of the configuration,
#   in order to track what has been changed between since the last time the Pod was running.

---
apiVersion: v1
kind: Service
metadata:
  name: opennms-core
  namespace: opennms
  labels:
    app: onms
    deployment: drift
spec:
  clusterIP: None
  ports:
  - port: 8980
    name: http
  - port: 8101
    name: karaf
  selector:
    app: onms

---
apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: onms
  namespace: opennms
  labels:
    app: onms
    deployment: drift
spec:
  serviceName: opennms-core
  replicas: 1 # The solution only allows 1 instance
  selector:
    matchLabels:
      app: onms
  template:
    metadata:
      labels:
        app: onms
        deployment: drift
    spec:
      terminationGracePeriodSeconds: 120
      initContainers:
      # Initialize OpenNMS Common Configuration
      # Requires the same image/version used at runtime: horizon-core-web
      - name: init-config
        #image: opennms/horizon-core-web:23.0.2-1
        image: opennms/horizon-core-web:bleeding # Not good for production
        imagePullPolicy: IfNotPresent
        command: [ bash, /init.sh ]
        env:
        - name: INSTANCE_ID # Must be the same on all OpenNMS, Sentinels and Minions
          value: OpenNMS
        - name: FEATURES_LIST
          value: opennms-es-rest,opennms-kafka-producer
        - name: CASSANDRA_SERVER
          value: cassandra.opennms.svc.cluster.local
        - name: CASSANDRA_REPFACTOR
          value: '2'
        - name: KAFKA_SERVER
          value: kafka.opennms.svc.cluster.local
        - name: ELASTIC_SERVER
          value: esdata.opennms.svc.cluster.local
        - name: ELASTIC_PASSWORD
          valueFrom:
            secretKeyRef:
              key: ELASTICSEARCH
              name: onms-passwords
        volumeMounts:
        - name: opennms-etc # Persistent volume for OpenNMS Configuration
          mountPath: /opennms-etc
        - name: opennms-config
          mountPath: /init.sh
          subPath: onms-core-init.sh
      # Initializes Newts keyspace on Cassandra/ScyllaDB (requires newts.cql)
      - name: init-newts
        image: cassandra:3.11.4
        imagePullPolicy: IfNotPresent
        command: [ sh, -c, 'cqlsh -f /opennms-etc/newts.cql $CASSANDRA_HOST' ]
        env:
        - name: CASSANDRA_HOST
          value: cassandra.opennms.svc.cluster.local
        volumeMounts:
        - name: opennms-etc
          mountPath: /opennms-etc
      - name: dependencies
        image: waisbrot/wait
        imagePullPolicy: IfNotPresent
        env:
        - name: TARGETS
          value: postgresql.opennms.svc.cluster.local:5432,cassandra.opennms.svc.cluster.local:9042,kafka.opennms.svc.cluster.local:9092,esdata.opennms.svc.cluster.local:9200
        - name: TIMEOUT
          value: '600'
      containers:
      - name: onms
        #image: opennms/horizon-core-web:23.0.2-1
        image: opennms/horizon-core-web:bleeding # Not good for production
        imagePullPolicy: IfNotPresent
        args:
        - -s
        ports:
        - containerPort: 8101
          name: karaf
        - containerPort: 8980
          name: http
        env:
        - name: TZ
          value: America/New_York
        - name: MEM_TOTAL_MB
          valueFrom:
            resourceFieldRef:
              resource: requests.memory
              divisor: 1Mi
        - name: CPU_TOTAL
          valueFrom:
            resourceFieldRef:
              resource: requests.cpu
        - name: JAVA_OPTS # Preferred way instead of opennms.conf
          value: -XX:+UseG1GC -Xms$(MEM_TOTAL_MB)m -Xmx$(MEM_TOTAL_MB)m
        - name: POSTGRES_HOST
          value: postgresql.opennms.svc.cluster.local
        - name: POSTGRES_PORT
          value: '5432'
        - name: POSTGRES_USER
          value: postgres
        - name: POSTGRES_PASSWORD
          valueFrom:
            secretKeyRef:
              key: POSTGRES
              name: onms-passwords
        - name: OPENNMS_DBNAME
          value: opennms
        - name: OPENNMS_DBUSER
          value: opennms
        - name: OPENNMS_DBPASS
          valueFrom:
            secretKeyRef:
              key: OPENNMS_DB
              name: onms-passwords
        volumeMounts:
        - name: opennms-etc
          mountPath: /opt/opennms/etc
        resources:
          limits:
            cpu: 4
            memory: 6Gi
          requests:
            cpu: 4
            memory: 4Gi
        readinessProbe:
          httpGet:
            path: /opennms/login.jsp
            port: http
          initialDelaySeconds: 15
          periodSeconds: 15
        livenessProbe:
          httpGet:
            path: /opennms/login.jsp
            port: http
          initialDelaySeconds: 30
          periodSeconds: 60
        lifecycle:
          preStop:
            exec:
              command:
              - bash
              - -c
              - 'echo "Shutting down minion..." && echo 1 > /opt/opennms/logs/opennms.pid && /opt/opennms/bin/opennms stop'
      volumes:
      - name: opennms-config
        configMap:
          name: opennms-config
  volumeClaimTemplates:
  - metadata:
      name: opennms-etc
    spec:
      accessModes:
      - ReadWriteOnce
      storageClassName: ssd
      resources:
        requests:
          storage: 1Gi # Cannnot be less than that in AWS for an EBS Volume
