# @author Alejandro Galue <agalue@opennms.org>
#
# WARNING: The sentinel user (uid: 999, gid: 997) cannot be used in OpenShift by default.
# TODO: Fix the sentinel overlay handling on the image.

---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: sentinel
  namespace: opennms
  labels:
    app: sentinel
    deployment: drift
spec:
  replicas: 2
  selector:
    matchLabels:
      app: sentinel
  template:
    metadata:
      labels:
        app: sentinel
        deployment: drift
    spec:
      terminationGracePeriodSeconds: 60
      affinity:
        podAntiAffinity:
          preferredDuringSchedulingIgnoredDuringExecution:
          - weight: 100
            podAffinityTerm:
              topologyKey: kubernetes.io/hostname
              labelSelector:
                matchExpressions:
                - key: app
                  operator: In
                  values:
                  - onms
      initContainers:
      - name: initialization
        image: opennms/sentinel:bleeding
        imagePullPolicy: IfNotPresent
        command: [ bash, /init.sh ]
        env:
        - name: INSTANCE_ID
          value: OpenNMS
        volumeMounts:
        - name: etc-overlay
          mountPath: /etc-overlay
        - name: opennms-config
          mountPath: /init.sh
          subPath: onms-sentinel-init.sh
      - name: wait-for-dependencies
        image: waisbrot/wait
        imagePullPolicy: IfNotPresent
        env:
        - name: TARGETS
          value: opennms-core.opennms.svc.cluster.local:8980
        - name: TIMEOUT
          value: '600'
      containers:
      - name: sentinel
        image: opennms/sentinel:bleeding
        imagePullPolicy: IfNotPresent
        args:
          - -d
        ports:
        - containerPort: 8301
          name: karaf
        env:
        - name: JAVA_OPTS
          value: -XX:+UnlockExperimentalVMOptions -XX:+UseCGroupMemoryLimitForHeap
        - name: POSTGRES_HOST
          value: postgresql.opennms.svc.cluster.local
        - name: POSTGRES_PORT
          value: '5432'
        - name: POSTGRES_USER
          value: postgres
        - name: POSTGRES_PASSWORD
          valueFrom:
            secretKeyRef:
              key: POSTGRES
              name: onms-passwords
        - name: POSTGRES_DB
          value: opennms
        - name: OPENNMS_HTTP_URL
          value: http://opennms-core.opennms.svc.cluster.local:8980/opennms
        - name: SENTINEL_LOCATION
          value: Sentinel
        - name: OPENNMS_HTTP_USER
          value: admin
        - name: OPENNMS_HTTP_PASS
          valueFrom:
            secretKeyRef:
              key: OPENNMS_UI_ADMIN
              name: onms-passwords
        volumeMounts:
        - name: opennms-config
          mountPath: /opt/sentinel/deploy/features.xml
          subPath: onms-sentinel-features.xml
        - name: etc-overlay
          mountPath: /opt/sentinel-etc-overlay
        resources:
          limits:
            cpu: 1
            memory: 2Gi
          requests:
            cpu: 500m
            memory: 1Gi
        lifecycle:
          preStop:
            exec:
              command: [ bash, -c, /opt/sentinel/bin/stop ]
        readinessProbe:
          tcpSocket:
            port: karaf
          initialDelaySeconds: 15
          periodSeconds: 10
        livenessProbe:
          tcpSocket:
            port: karaf
          initialDelaySeconds: 60
          periodSeconds: 60
      volumes:
      - name: etc-overlay
        emptyDir: {}
      - name: opennms-config
        configMap:
          name: opennms-config
