# @author Alejandro Galue <agalue@opennms.org>

---
apiVersion: v1
kind: Service
metadata:
  name: opennms-ui
  namespace: opennms
  labels:
    app: onms-ui
    deployment: drift
spec:
  clusterIP: None
  ports:
  - port: 8980
    name: http
  - port: 8101
    name: karaf
  selector:
    app: onms-ui

---
apiVersion: v1
kind: Service
metadata:
  name: ext-onms-ui
  namespace: opennms
  labels:
    app: onms-ui
    deployment: drift
  annotations:
    dns.alpha.kubernetes.io/external: onmsui.k8s.opennms.org.
spec:
  type: LoadBalancer
  ports:
  - port: 80
    targetPort: 8980
  selector:
    app: onms-ui

---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: onms-ui
  namespace: opennms
  labels:
    app: onms-ui
    deployment: drift
spec:
  replicas: 2
  selector:
    matchLabels:
      app: onms-ui
  template:
    metadata:
      labels:
        app: onms-ui
        deployment: drift
    spec:
      affinity:
        podAntiAffinity:
          preferredDuringSchedulingIgnoredDuringExecution:
          - weight: 1
            podAffinityTerm:
              labelSelector:
                matchExpressions:
                - key: app
                  operator: In
                  values:
                  - onms
              topologyKey: kubernetes.io/hostname
      initContainers:
      - name: wait-for-dependencies
        image: waisbrot/wait
        imagePullPolicy: IfNotPresent
        env:
        - name: TARGETS
          value: opennms-core.opennms.svc.cluster.local:8980
        - name: TIMEOUT
          value: '600'
      containers:
      - name: onms-ui
        image: opennms/horizon-core-web:bleeding
        imagePullPolicy: IfNotPresent
        command: [ /docker-entrypoint.sh, -s ]
        ports:
        - containerPort: 8101
          name: karaf
        - containerPort: 8980
          name: http
        env:
        - name: JAVA_OPTS
          value: -XX:+UnlockExperimentalVMOptions -XX:+UseCGroupMemoryLimitForHeap
        - name: POSTGRES_HOST
          value: postgresql.opennms.svc.cluster.local
        - name: POSTGRES_PORT
          value: '5432'
        - name: POSTGRES_USER
          value: postgres
        - name: POSTGRES_PASSWORD
          value: postgres
        - name: OPENNMS_DBNAME
          value: opennms
        - name: OPENNMS_DBUSER
          value: opennms
        - name: OPENNMS_DBPASS
          value: opennms
        volumeMounts:
        - name: onms-core-etc
          mountPath: /opt/opennms-etc-overlay/org.opennms.features.datachoices.cfg
          subPath: org.opennms.features.datachoices.cfg
        - name: onms-core-etc
          mountPath: /opt/opennms-etc-overlay/opennms.properties.d/newts.properties
          subPath: newts.properties
        - name: onms-ui-etc
          mountPath: /opt/opennms-etc-overlay/org.opennms.features.flows.persistence.elastic.cfg
          subPath: org.opennms.features.flows.persistence.elastic.cfg
        - name: onms-ui-etc
          mountPath: /opt/opennms-etc-overlay/eventconf.xml
          subPath: eventconf.xml
        - name: onms-ui-etc
          mountPath: /opt/opennms-etc-overlay/service-configuration.xml
          subPath: service-configuration.xml
        - name: onms-ui-etc
          mountPath: /opt/opennms-etc-overlay/opennms.properties.d/webui.properties
          subPath: webui.properties
        - name: onms-ui-etc
          mountPath: /opt/opennms-jetty-webinf-overlay/applicationContext-spring-security.xml
          subPath: applicationContext-spring-security.xml
        resources:
          limits:
            cpu: 1
            memory: 4Gi
          requests:
            cpu: 500m
            memory: 2Gi
        readinessProbe:
          httpGet:
            path: /
            port: http
          initialDelaySeconds: 15
        livenessProbe:
          httpGet:
            path: /
            port: http
          initialDelaySeconds: 60
          periodSeconds: 60
      volumes:
      - name: onms-core-etc
        configMap:
          name: opennms-core-overlay
      - name: onms-ui-etc
        configMap:
          name: opennms-ui-overlay
