# @author Alejandro Galue <agalue@opennms.org>
#
# Using StatefulSets for Minions only to have a unique and immutable MINION_ID
# This Pod includes 2 containers, one for the Minion and one for the GRPC Server for NX-OS
#
# WARNING:
# - The default images are based on OpenJDK, but Oracle JDK is recommended for production.
#   Oracle JDK based images are available at no42org. For example: no42org/minion:23.0.2
# - The image agalue/sentinel:23.0.2-oracle-jdk8u201 refers to the upcoming version of OpenNMS (unstable)
#
# Java 8 Issues:
# - -XX:+UnlockExperimentalVMOptions and -XX:+UseCGroupMemoryLimitForHeap won't work
# - -XX:ParallelGCThreads and -XX:ConcGCThreads might require to be updated.
#    Although, Runtime.getRuntime().availableProcessors() seems to respect the CPU limitations.

---
apiVersion: v1
kind: Service
metadata:
  name: minion
  namespace: opennms
  labels:
    app: minion
    deployment: drift
spec:
  clusterIP: None
  ports:
  - port: 8201
    name: karaf
  - port: 161
    name: traps
    targetPort: 1161
  - port: 514
    name: syslog
    targetPort: 1514
  - port: 8877
    name: netflow5
  - port: 4729
    name: netflow9
  - port: 6343
    name: sflow
  - port: 4738
    name: ipfix
  - port: 50001
    name: nxos-udp
  - port: 50002
    name: nxos-grpc
  selector:
    app: minion

---
apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: minion
  namespace: opennms
  labels:
    app: minion
    deployment: drift
spec:
  serviceName: minion
  replicas: 2
  selector:
    matchLabels:
      app: minion
  template:
    metadata:
      labels:
        app: minion
        deployment: drift
    spec:
      initContainers:
      - name: init-sysctl
        image: busybox
        command: # Allow ICMP as non-root
        - sysctl
        - -w
        - net.ipv4.ping_group_range=0 429496729
        securityContext:
          privileged: true
      # Requires the same image/version used at runtime: minion
      - name: init-config
        #image: agalue/minion:23.0.2-oracle-jdk8u201
        image: opennms/minion:bleeding # Not good for production
        imagePullPolicy: IfNotPresent
        command: [ bash, /init.sh ]
        env:
        - name: INSTANCE_ID # Must be the same on all OpenNMS, Sentinels and Minions
          value: OpenNMS
        volumeMounts:
        - name: etc-overlay
          mountPath: /etc-overlay
        - name: opennms-config
          mountPath: /init.sh
          subPath: onms-minion-init.sh
      - name: dependencies
        image: waisbrot/wait
        imagePullPolicy: IfNotPresent
        env:
        - name: TARGETS
          value: kafka.opennms.svc.cluster.local:9092,opennms-core.opennms.svc.cluster.local:8980
        - name: TIMEOUT
          value: '600'
      containers:
      - name: minion
        #image: agalue/minion:23.0.2-oracle-jdk8u201
        image: opennms/minion:bleeding # Not good for production
        imagePullPolicy: IfNotPresent
        args:
        - -f
        env:
        - name: MINION_ID
          valueFrom:
            fieldRef:
              fieldPath: metadata.name
        - name: MEM_TOTAL_MB
          valueFrom:
            resourceFieldRef:
              resource: requests.memory
              divisor: 1Mi
        - name: JAVA_OPTS
          value: -XX:+UseG1GC -Xms$(MEM_TOTAL_MB)m -Xmx$(MEM_TOTAL_MB)m -XX:+PrintFlagsFinal
        - name: MINION_LOCATION
          value: Kubernetes
        - name: OPENNMS_HTTP_URL
          value: http://opennms-core.opennms.svc.cluster.local:8980/opennms
        - name: OPENNMS_HTTP_USER
          value: admin
        - name: OPENNMS_HTTP_PASS
          valueFrom:
            secretKeyRef:
              key: OPENNMS_UI_ADMIN
              name: onms-passwords
        - name: KAFKA_RPC_ACKS
          value: '1'
        - name: KAFKA_RPC_BOOTSTRAP_SERVERS
          value: kafka.opennms.svc.cluster.local:9092
        - name: KAFKA_SINK_BOOTSTRAP_SERVERS
          value: kafka.opennms.svc.cluster.local:9092
        ports:
        - containerPort: 1162
          name: traps
        - containerPort: 1514
          name: syslog
        - containerPort: 8201
          name: karaf
        - containerPort: 50001
          name: nxos-udp
        - containerPort: 8877
          name: netflow5
        - containerPort: 4729
          name: netflow9
        - containerPort: 6343
          name: sflow
        - containerPort: 4738
          name: ipfix
        volumeMounts:
        - name: etc-overlay
          mountPath: /opt/minion-etc-overlay
        resources:
          limits:
            cpu: 500m
            memory: 2Gi
          requests:
            cpu: 200m
            memory: 1Gi
        readinessProbe:
          tcpSocket:
            port: karaf
          initialDelaySeconds: 15
          periodSeconds: 10
        livenessProbe:
          tcpSocket:
            port: karaf
          initialDelaySeconds: 60
          periodSeconds: 60
      - name: nxos-grpc
        image: agalue/opennms-nxos-grpc:latest
        env:
          - name: BOOTSTRAP_SERVERS
            value: kafka.opennms.svc.cluster.local:9092
          - name: MINION_LOCATION
            value: Kubernetes
          - name: MINION_ID
            valueFrom:
              fieldRef:
                fieldPath: metadata.name
          - name: PORT
            value: '50002'
          - name: TOPIC
            value: OpenNMS.Sink.Telemetry-NXOS
        ports:
        - containerPort: 50002
          name: nxos-grpc
      volumes:
      - name: etc-overlay
        emptyDir: {}
      - name: opennms-config
        configMap:
          name: opennms-config
