# @author Alejandro Galue <agalue@opennms.org>
#
# WARNING:
# - The opennms process runs as root, which is not allowed on OpenShift
#
# Java 8 Issues:
# - -XX:+UnlockExperimentalVMOptions and -XX:+UseCGroupMemoryLimitForHeap won't work
# - -XX:ParallelGCThreads and -XX:ConcGCThreads should be updated. This is because
#    Runtime.getInstance().getAvailableProcessors() will return the number of cores of the host.

---
apiVersion: v1
kind: Service
metadata:
  name: opennms-ui
  namespace: opennms
  labels:
    app: onms-ui
    deployment: drift
spec:
  ports:
  - port: 8980
    name: http
  - port: 8101
    name: karaf
  selector:
    app: onms-ui

---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: onms-ui
  namespace: opennms
  labels:
    app: onms-ui
    deployment: drift
spec:
  replicas: 2
  selector:
    matchLabels:
      app: onms-ui
  template:
    metadata:
      labels:
        app: onms-ui
        deployment: drift
    spec:
      affinity:
        podAntiAffinity:
          requiredDuringSchedulingIgnoredDuringExecution:
          - topologyKey: kubernetes.io/hostname
            labelSelector:
              matchExpressions:
              - key: app
                operator: In
                values:
                - onms
      initContainers:
      # Initialize OpenNMS UI Configuration
      # Requires the same image/version used at runtime: horizon-core-web
      - name: init-config
        image: agalue/horizon-core-web:23.0.2-oracle-jdk8u201
        #image: opennms/horizon-core-web:bleeding # Not good for production
        imagePullPolicy: IfNotPresent
        command: [ bash, /init.sh ]
        env:
        - name: INSTANCE_ID # Must be the same on all OpenNMS, Sentinels and Minions
          value: OpenNMS
        - name: CASSANDRA_SERVER
          value: cassandra.opennms.svc.cluster.local
        - name: ELASTIC_SERVER
          value: esdata.opennms.svc.cluster.local
        - name: ELASTIC_PASSWORD
          valueFrom:
            secretKeyRef:
              key: ELASTICSEARCH
              name: onms-passwords
        - name: GF_SECURITY_ADMIN_PASSWORD
          valueFrom:
            secretKeyRef:
              key: GRAFANA_UI_ADMIN
              name: onms-passwords
        - name: GRAFANA_URL
          value: http://grafana.opennms.svc.cluster.local:3000
        - name: GRAFANA_PUBLIC_URL
          value: https://grafana.k8s.opennms.org
        volumeMounts:
        - name: etc-overlay
          mountPath: /opt/opennms-etc-overlay
        - name: web-overlay
          mountPath: /opt/opennms-jetty-webinf-overlay
        - name: opennms-config
          mountPath: /init.sh
          subPath: onms-ui-init.sh
      - name: dependencies
        image: waisbrot/wait
        imagePullPolicy: IfNotPresent
        env:
        - name: TARGETS
          value: opennms-core.opennms.svc.cluster.local:8980,grafana.opennms.svc.cluster.local:3000
        - name: TIMEOUT
          value: '600'
      containers:
      - name: onms-ui
        image: agalue/horizon-core-web:23.0.2-oracle-jdk8u201
        #image: opennms/horizon-core-web:bleeding # Not good for production
        imagePullPolicy: IfNotPresent
        command: [ /docker-entrypoint.sh, -s ]
        ports:
        - containerPort: 8101
          name: karaf
        - containerPort: 8980
          name: http
        env:
        - name: MEM_TOTAL_MB
          valueFrom:
            resourceFieldRef:
              resource: requests.memory
              divisor: 1Mi
        - name: JAVA_OPTS # Preferred way instead of opennms.conf
          value: -XX:+UseG1GC -Xms$(MEM_TOTAL_MB)m -Xmx$(MEM_TOTAL_MB)m -XX:+PrintFlagsFinal
        - name: POSTGRES_HOST
          value: postgresql.opennms.svc.cluster.local
        - name: POSTGRES_PORT
          value: '5432'
        - name: POSTGRES_USER
          value: postgres
        - name: POSTGRES_PASSWORD
          valueFrom:
            secretKeyRef:
              key: POSTGRES
              name: onms-passwords
        - name: OPENNMS_DBNAME
          value: opennms
        - name: OPENNMS_DBUSER
          value: opennms
        - name: OPENNMS_DBPASS
          valueFrom:
            secretKeyRef:
              key: OPENNMS_DB
              name: onms-passwords
        volumeMounts:
        - name: etc-overlay
          mountPath: /opt/opennms-etc-overlay
        - name: web-overlay
          mountPath: /opt/opennms-jetty-webinf-overlay
        resources:
          limits:
            cpu: 2
            memory: 6Gi
          requests:
            cpu: 500m
            memory: 4Gi
        readinessProbe:
          httpGet:
            path: /opennms/login.jsp
            port: http
          initialDelaySeconds: 15
          periodSeconds: 15
        livenessProbe:
          httpGet:
            path: /opennms/login.jsp
            port: http
          initialDelaySeconds: 30
          periodSeconds: 60
      volumes:
      - name: etc-overlay
        emptyDir: {}
      - name: web-overlay
        emptyDir: {}
      - name: opennms-config
        configMap:
          name: opennms-config
