# @author Alejandro Galue <agalue@opennms.org>
#
# JVMFLAGS should be consistent with resources.requests.memory
#
# WARNING: For some reason, full FQDNs are required for ZOO_SERVERS; otherwise, the leader election fails.
# WARNING: The zookeeper user (uid: 1000, gid: 1000) cannot be used in OpenShift by default.

apiVersion: v1
kind: Service
metadata:
  name: zookeeper
  namespace: opennms
  labels:
    app: zk
    deployment: drift
spec:
  ports:
  - port: 2888
    name: server
  - port: 3888
    name: leader-election
  - port: 2181
    name: client
  clusterIP: None
  selector:
    app: zk

---
apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: zk
  namespace: opennms
  labels:
    app: zk
    deployment: drift
spec:
  serviceName: zookeeper
  replicas: 3 # The solution is designed for 3 instances
  podManagementPolicy: Parallel
  selector:
    matchLabels:
      app: zk
  template:
    metadata:
      labels:
        app: zk
        deployment: drift
    spec:
      terminationGracePeriodSeconds: 300
      initContainers:
      - name: generate-zooid
        image: busybox
        imagePullPolicy: IfNotPresent
        securityContext:
          privileged: true
        command:
        - sh
        - -c
        - ORD=${HOSTNAME##*-}; MYID=$((ORD+1)); echo $MYID > /data/myid
        volumeMounts:
        - name: zk-data
          mountPath: /data
      containers:
      - name: zk
        image: zookeeper:3.4.13
        imagePullPolicy: IfNotPresent
        env:
        - name: ZOO_SERVERS
          value: server.1=zk-0.zookeeper.opennms.svc.cluster.local:2888:3888 server.2=zk-1.zookeeper.opennms.svc.cluster.local:2888:3888 server.3=zk-2.zookeeper.opennms.svc.cluster.local:2888:3888
        - name: ZOO_TICK_TIME
          value: '2000'
        - name: ZOO_INIT_LIMIT
          value: '10'
        - name: ZOO_SYNC_LIMIT
          value: '5'
        - name: JVMFLAGS
          value: -Xmx256M -Xms128M
        ports:
        - containerPort: 2888
          name: peer
        - containerPort: 3888
          name: leader-election
        - containerPort: 2181
          name: client
        volumeMounts:
        - name: zk-data
          mountPath: /data
        resources:
          requests:
            memory: 256Mi
            cpu: 100m
        readinessProbe:
          exec:
            command:
            - sh
            - -c
            - '[ "imok" = "$(echo ruok | nc 127.0.0.1 2181)" ]'
          initialDelaySeconds: 10
          periodSeconds: 10
        livenessProbe:
          tcpSocket:
            port: client
          initialDelaySeconds: 60
          periodSeconds: 60
  volumeClaimTemplates:
  - metadata:
      name: zk-data
    spec:
      accessModes:
      - ReadWriteOnce
      storageClassName: aws-ebs
      resources:
        requests:
          storage: 4Gi