apiVersion: v1
kind: Pod
metadata:
  name: udpgen-m0
  namespace: opennms
  labels:
    app: udpgen
spec:
  securityContext:
    runAsUser: 1000
    fsGroup: 1000
  affinity:
    podAntiAffinity:
      preferredDuringSchedulingIgnoredDuringExecution:
      - weight: 100
        podAffinityTerm:
          topologyKey: kubernetes.io/hostname
          labelSelector:
            matchExpressions:
            - key: app
              operator: In
              values:
              - minion
  containers:
  - name: udpgen
    image: opennms/udpgen:latest
    args: [ "/udpgen", "-i", "-x", "netflow9", "-r", "1800", "-h", "minion-0.minion.opennms.svc.cluster.local", "-p", "4729" ]
    imagePullPolicy: IfNotPresent
    resources:
      limits:
        memory: 512Mi
        cpu: 200m
      requests:
        memory: 256Mi
        cpu: 100m
---
apiVersion: v1
kind: Pod
metadata:
  name: udpgen-m1
  namespace: opennms
  labels:
    app: udpgen
spec:
  securityContext:
    runAsUser: 1000
    fsGroup: 1000
  affinity:
    podAntiAffinity:
      preferredDuringSchedulingIgnoredDuringExecution:
      - weight: 100
        podAffinityTerm:
          topologyKey: kubernetes.io/hostname
          labelSelector:
            matchExpressions:
            - key: app
              operator: In
              values:
              - minion
  containers:
  - name: udpgen
    image: opennms/udpgen:latest
    args: [ "/udpgen", "-i", "-x", "netflow9", "-r", "1800", "-h", "minion-1.minion.opennms.svc.cluster.local", "-p", "4729" ]
    imagePullPolicy: IfNotPresent
    resources:
      limits:
        memory: 512Mi
        cpu: 200m
      requests:
        memory: 256Mi
        cpu: 100m

# minion Netflow-9-Listener port 4729/udp
# minion Netflow-5-Listener port 8877/udp
