# @author Alejandro Galue <agalue@opennms.org>

---
apiVersion: sources.knative.dev/v1alpha1
kind: KafkaSource
metadata:
  name: kafka-source
  namespace: default
spec:
  consumerGroup: knative-group
  bootstrapServers: kafka.opennms.svc.cluster.local:9092
  topics: K8S-alarms-json
  sink:
    ref:
      apiVersion: serving.knative.dev/v1
      kind: Service
      name: slack-forwarder