# @author Alejandro Galue <agalue@opennms.org>

---
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: opennms

commonLabels:
  environment: minikube

commonAnnotations:
  owner: agalue@opennms.org

resources:
- ../namespace/opennms.yaml
- ../manifests/postgresql.yaml
- ../manifests/zookeeper.yaml
- ../manifests/kafka.yaml
- ../manifests/elasticsearch.data.yaml
- ../manifests/cassandra.yaml
- ../manifests/opennms.core.yaml
- ../manifests/opennms.minion.yaml
- ../manifests/opennms.sentinel.yaml

configMapGenerator:
- name: opennms-config
  files:
  - ../config/onms-core-init.sh
  - ../config/onms-minion-init.sh
  - ../config/onms-sentinel-features.xml
  - ../config/onms-sentinel-init.sh
  - ../config/onms-ui-init.sh

generatorOptions:
  disableNameSuffixHash: true

secretGenerator:
- name: onms-passwords
  envCommand: cat passwords.env

patchesJson6902:
- path: patches/postgres.yaml 
  target:
    group: apps
    version: v1
    kind: StatefulSet
    name: postgres
- path: patches/zookeeper.yaml
  target:
    group: apps
    version: v1
    kind: StatefulSet
    name: zk
- path: patches/kafka.yaml
  target:
    group: apps
    version: v1
    kind: StatefulSet
    name: kafka
- path: patches/elasticsearch.yaml
  target:
    group: apps
    version: v1
    kind: StatefulSet
    name: esdata
- path: patches/cassandra.yaml
  target:
    group: apps
    version: v1
    kind: StatefulSet
    name: cassandra
- path: patches/opennms.core.yaml
  target:
    group: apps
    version: v1
    kind: StatefulSet
    name: onms
- path: patches/opennms.minion.yaml
  target:
    group: apps
    version: v1
    kind: StatefulSet
    name: minion
- path: patches/opennms.sentinel.yaml
  target:
    group: apps
    version: v1
    kind: Deployment
    name: sentinel
