# @author Alejandro Galue <agalue@opennms.org>
#
# Warning: this excludes Cassandra to reduce the overhead on Minikube

---
bases:
- ../reduced

patches:
- patches/cassandra.yaml
- patches/kafka.manager.yaml
- patches/opennms.core.yaml
- patches/opennms.sentinel.yaml
- patches/external-access.yaml
