apiVersion: v1
kind: Service
metadata:
  name: flink-taskmanager
spec:
  clusterIP: None
  ports:
  - name: rpc
    port: 6122
  - name: prom
    port: 9999
  selector:
    app: flink
    component: taskmanager
