# @author Alejandro Galue <agalue@opennms.org>

---
apiVersion: extensions/v1beta1
kind: Ingress
metadata:
  name: ingress-rules
  namespace: opennms
spec:
  tls:
    - secretName: opennms-ingress-cert
      hosts:
        - onms.__DOMAIN__
        - grafana.__DOMAIN__
        - hasura.__DOMAIN__
        - kibana.__DOMAIN__
        - elastichq.__DOMAIN__
        - kafka-manager.__DOMAIN__
        - tracing.__DOMAIN__
  rules:
    - host: onms.__DOMAIN__
      http:
        paths:
          - path: /
            backend:
              serviceName: opennms-core
              servicePort: 8980
    - host: grafana.__DOMAIN__
      http:
        paths:
          - path: /
            backend:
              serviceName: grafana
              servicePort: 3000
    - host: hasura.__DOMAIN__
      http:
        paths:
          - path: /
            backend:
              serviceName: hasura
              servicePort: 8080
    - host: kafka-manager.__DOMAIN__
      http:
        paths:
          - path: /
            backend:
              serviceName: kafka-manager
              servicePort: 9000
    - host: kibana.__DOMAIN__
      http:
        paths:
          - path: /
            backend:
              serviceName: kibana
              servicePort: 5601
    - host: elastichq.__DOMAIN__
      http:
        paths:
          - path: /
            backend:
              serviceName: elastichq
              servicePort: 5000
    - host: tracing.__DOMAIN__
      http:
        paths:
          - path: /
            backend:
              serviceName: onms-tracing-query
              servicePort: 16686
